### ISSUE TITLE
Enhancement Deployment server

### ISSUE THREAD

**Issue by neusse** [ChrisYounger/config_explorer#14]
Ability for btool to check at a basic level the conf files in the $SPLUNK_HOME/etc/deployment-apps directory.

**Comment by ChrisYounger** [comment]
Great suggestion, thank you. I will add this in the next few days.

**Comment by ChrisYounger** [comment]
release 1.2.5 on splunkbase now has this functionality. Thanks for the suggestion.

**Comment by neusse** [comment]
Thanks, this is great news.  I have had different clients that have had a
security and an ops group both editing conf files on separate apps on the
deployment server.  This is huge since now they can see if they are
stepping on each other.

Thanks again!

Best Regards,

*George Neusse*

=============================================

“A computer lets you make more mistakes faster than any other invention
with the possible exceptions of handguns and Tequila.”
― Mitch Ratcliffe
<https://www.goodreads.com/author/show/765026.Mitch_Ratcliffe>
