### ISSUE TITLE
Ability to see who saved a file change

### ISSUE THREAD

**Issue by manderso7** [ChrisYounger/config_explorer#16]
I see that I can save a file from the UI, which is great. But will there be a way to see who saved the file, and when?
Version control is useful, but it's only going to show the file and it's ownership by the splunk user. Whenever we go to change a file in the cli, we do so as the splunk user, so this would be amazing to see.
Please let me know if you have questions.

**Comment by ChrisYounger** [comment]
Yes this is a limitation of the way its been implemented. However there is logging that will show who saved a file. On the "home" tab there is a link at the bottom to "logging" which will take you to a search like so: 

`index=_internal source=*config_explorer.log`

Hope this helps.

**Comment by manderso7** [comment]
Yes thank you, that's what I needed.

**Comment by manderso7** [comment]
Not sure if this should be in the same issue or not. If not, I apologize.
I've noticed that in the config_explorer.log file, after a file is saved, there are additional fields in the event, param1 & reason, both are blank in all my save action events. Can I add values to these fields when I save the file in question using config_explorer?
Thanks again

**Comment by ChrisYounger** [comment]
There is no configuration that allows changing what is logged. 

However if you know python well you could try make modifications to `etc/apps/config_explorer/bin/config_explorer.py`

**Comment by manderso7** [comment]
Ok, thank you.
