### ISSUE TITLE
Config Explorer error

### ISSUE THREAD

**Issue by bshuler** [ChrisYounger/config_explorer#17]
this is a continuation of 

https://answers.splunk.com/answers/826273/config-explorer-error.html

as answers is read only for a few days.

I am also having the issue and I ran the suggested command. output below:

C:\Program Files\Splunk>bin\splunk.exe cmd python
Python 2.7.17 (default, Apr 29 2020, 03:20:34) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, subprocess; env_copy = os.environ.copy(); p = subprocess.Popen(['bin\\splunk', 'btool', 'check', '--debug'], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=False, env=env_copy); o = p.communicate(); o
('Checking: C:\\Program Files\\Splunk\\etc\\users\\bshuler\\search\\local\\ui-tour.conf\r\n<REPEATED, REDACTED FOR BREVITY>Checking: C:\\Program Files\\Splunk\\etc\\system\\local\\web.conf\r\n', None)
>>> quit()

**Comment by ChrisYounger** [comment]
Thanks for reporting this. I have now been able to reproduce the problem and I have a fix almost complete that I will push soon.

**Comment by ChrisYounger** [comment]
OK Please download version 1.4.9 and give it a try. Let me know if you still have problems. Thanks for bringing this problem to my attention.

**Comment by bshuler** [comment]
Looks good, works. Thanks!
