### ISSUE TITLE
Cannot use app on fresh install

### ISSUE THREAD

**Issue by tmontney** [ChrisYounger/config_explorer#18]
After installation, rebooted Splunk, launched app:

> An error occurred!
> 
> fs:
> 
> 
> Bare surrogate pair in string

Splunk Enterprise 8.1.0
Ubuntu 18.04
Splunk is running as non-root.

I assume the error starts at line 242 in https://github.com/ChrisYounger/config_explorer/blob/master/bin/config_explorer.py.

**Comment by ChrisYounger** [comment]
Hmm strange. I am using config explorer on 8.1 without issues.  The error seems to be occuring where it is trying to pre-load the filesystem contents. The error should go away if you set `cache_file_depth = 0` in the `local/config_explorer.conf`

I expect your have a file or folder somewhere with a funny name that is breaking config explorer. If you can figure out what file that is, then I can try fix config explorer

Thanks for the reporting the issue

**Comment by tmontney** [comment]
The only other thing I did was create an app with a "3" in the name (no spaces). Otherwise, it's a pretty vanilla installation.

Applied the change, works fine now.

**Comment by ChrisYounger** [comment]
OK cool, but you might find this error comes up again if you try to navigate to the specific folder that has the weirdly named file in it.    

With further research it seems a "surrogate pair" is an extended length utf string - maybe an emoji or a Chinese symbol.  I will see if I can update config explorer to deal with these files/folders better

**Comment by tmontney** [comment]
I navigated to my app's folder, no issue. If you're able to update the error message to call out the directory/file in question, that'd help a lot. Otherwise, I have no idea which folder is problematic.
