### ISSUE TITLE
Ability to choose what conf to run a btool against

### ISSUE THREAD

**Issue by ghost** [ChrisYounger/config_explorer#23]
Running a btool from the app is great, but it would be useful to choose which conf file it can be run against.

**Comment by ChrisYounger** [comment]
Hi Mike, are you able to provide more details on what you mean? Config Explorer already allows you to run btool on a specific file. You can right-click on any .conf file and it will provide an option to "run btool on this file". Secondly, you can click the little "light bulb" icon and this will show all the config files that exist, and allow you to run btool on any.

**Comment by ghost** [comment]
That's what we needed, didn't know it existed. Thank you.
